### PR TITLE
Major Cleanup

### PR DESCRIPTION
**Pull request by jacksontj**
This has a lot of cleanup involved, so I'll attempt to summarize (more details are in the commit messages):

- cleanup the client to move all non-client-specific methods into standalone functions
- simplify client interface (instead of having 4-- which would have been 8, we have 2)
- change the interface to return errors (This is a **breaking** change, but is required)
- make `Datacenter` for the client private
- add method to lookup for a specific datacenter

### CODE REVIEW

**Comment by kahuang** [comment]
Before merging, need to make sure downstream dependencies pin to the right version (or at least aware of the change)

**Comment by svrana** [comment]
Planning on adding back ability to get all hosts by region?

**Comment by jacksontj** [comment]
@svrana I just added that-- but I think I want to change the `New` methods for the client, so we have 1 that is auto lookup and one that you have to provide an `InstanceIdentity`

**Comment by jacksontj** [comment]
@kahuang glide/dep should already be pinned to the version (lock files), we shouldn't need to do more? If we want we can start doing release versions for this lib, but its small enough that I think master is probably okay.

**Pull request merged**
